env:
  singleUserMode: false
  registration: {}
  # emailDomainBlacklist: "example1.com|example2.com"
  # emailDomainWhitelist: "example1.com|example2.com"
  defaultLanguage: "en"
  smtp:
    server: smtp.mailgun.org
    port: "587"
    login: ""
    address: notifications@example.com
    reply_to: ""
    opensslVerifyMode: "peer"
    aliasHostname: ""
    domain: ""
  assets:
    paperclipRootPath: ""
    paperclipRootUrl: ""
    cdnHost: ""

  s3:
    enabled: false
    # Enables support for gcs
    gcs: false
    # These come from minio by default, set here to override
    bucket: ""
    awsAccessKeyId: ""
    awsSecretAccessKey: ""
    endpoint: ""
    region: ""
    aliasHostname: ""
    protocol: "http"
    hostname: "mastodon-minio:9000"

web:
  image: ghcr.io/glitch-soc/mastodon
  imageTag: latest
  imagePullPolicy: IfNotPresent
  servicePort: 80
  containerPort: 3000
  concurrency: 5
  maxThreads: 5
  logLevel: info
  keepMediaDays: 7
  maintenanceHour: 3
  ingress:
    host: SET_YOUR_DOMAIN
  persistentVolume:
    system:
      accessMode: ReadWriteOnce
      size: 8Gi
    assets:
      accessMode: ReadWriteOnce
      size: 8Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

streaming:
  image: ghcr.io/glitch-soc/mastodon
  imageTag: latest
  imagePullPolicy: IfNotPresent
  servicePort: 4000
  containerPort: 4000
  clusterSize: 5
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

sidekiq:
  image: ghcr.io/glitch-soc/mastodon
  imageTag: latest
  imagePullPolicy: IfNotPresent
  parallelism: 2
  defaultQparallelism: 2
  pullQparallelism: 5
  pushQparallelism: 2
  mailersQparallelism: 2
  defaultQreplicas: 1
  pullQreplicas: 1
  pushQreplicas: 1
  mailersQreplicas: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

redis:
  enabled: true
  image:
    tag: 6.2-alpine
  servicePort: 6379
  containerPort: 6379
  storage:
    requestedSize: 8Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

externalRedis:
  url:
  existingSecret: ""
  existingSecretUrlKey: "redis-url"

postgres:
  enabled: true
  image:
    tag: "14.2"
  imagePullPolicy: IfNotPresent
  userDatabase:
    name: mastodon
    user: mastodon
  storage:
    requestedSize: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

externalPostgresql:
  host: host
  port: 5432
  database: database
  user: user
  password: ""
  existingSecret: ""
  existingSecretPasswordKey: "postgres-password"

elasticsearch:
  enabled: true
  replicas: 1
  minimumMasterNodes: 1

minio:
  enabled: true
  mode: standalone
  replicas: 1

  # Change these!!!
  rootUser: BkU9Gc8wIygQC8kghBhN
  rootPassword: mOGpRFdMyyiBDTXdhBZIDGU9uWHqVtauYvBDgPgO

  buckets:
    - name: mastodon
      policy: public

### Secrets, change these.
# https://docs.joinmastodon.org/admin/config/#secrets
paperclipSecret: ""
secretKeyBase: ""
otpSecret: ""
smtpPassword: ""
vapidPrivateKey: ""
vapidPublicKey: ""
