apiVersion: v1
kind: Secret
metadata:
  name: {{ template "web.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "web"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  PAPERCLIP_SECRET: {{ .Values.paperclipSecret | quote }}
  SECRET_KEY_BASE: {{ .Values.secretKeyBase | quote }}
  OTP_SECRET: {{ .Values.otpSecret | quote }}
  SMTP_PASSWORD: {{ .Values.smtpPassword | quote }}
  DB_PASS: {{ .Values.postgres.userDatabase.password | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.env.s3.awsSecretAccessKey | default .Values.minio.secretKey | quote }}
